/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Prunus_Pendula.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import Glow from './Glow'

export function Model(props) {
	const { nodes, materials } = useGLTF('/Prunus_Pendula.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Prunus_pendula__A001_1.geometry}
				material={materials.Material__2}
			/>
			<Glow scale={1.2} near={-25} color={'#ff0000'} />
			<mesh
				geometry={nodes.Prunus_pendula__A001_2.geometry}
				material={materials.Material__3}
			/>
		</group>
	)
}

useGLTF.preload('/Prunus_Pendula.glb')
